# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Users/DELL/.jdks/dragonwell-21.0.12
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.vfs.watch=false
kotlin.daemon.jvmargs=-Xmx1024m
org.gradle.parallel=false
kotlin.incremental=false
ksp.incremental=false
