package com.notify.core.model

import java.util.UUID

/**
 * Origin of a queued track item.
 */
enum class QueueOrigin {
    /** Track queued explicitly by user (Play Next, Add to Queue). */
    USER,
    /** Track loaded from a user-created local or imported playlist. */
    PLAYLIST,
    /** Track dynamically generated by the Watch Next / Radio adapter. */
    RADIO
}

/**
 * An item in the active playback queue.
 * Each queue item has a unique queueId allowing the same track to appear multiple times in a queue.
 */
data class QueueEntry(
    val queueId: String = UUID.randomUUID().toString(),
    val track: Track,
    val origin: QueueOrigin = QueueOrigin.USER,
    val playbackOrigin: PlaybackOrigin = PlaybackOrigin.UNKNOWN
)
